"""Added fields for local & remote sockets to network table

Revision ID: 140c0dd3605
Revises: 20c114cc162
Create Date: 2015-11-29 14:40:04.862179

"""

# revision identifiers, used by Alembic.
revision = '140c0dd3605'
down_revision = '20c114cc162'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('lhost', sa.String(length=100), nullable=True))
    op.add_column('networks', sa.Column('lport', sa.Integer(), nullable=True))
    op.add_column('networks', sa.Column('rhost', sa.String(length=100), nullable=True))
    op.add_column('networks', sa.Column('rport', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'rport')
    op.drop_column('networks', 'rhost')
    op.drop_column('networks', 'lport')
    op.drop_column('networks', 'lhost')
    ### end Alembic commands ###
