"""Added SSL fields in network table.

Revision ID: 50135956b24
Revises: 140c0dd3605
Create Date: 2015-12-10 20:46:37.397744

"""

# revision identifiers, used by Alembic.
revision = '50135956b24'
down_revision = '140c0dd3605'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networks', sa.Column('ssl', sa.Boolean(), nullable=True))
    op.add_column('networks', sa.Column('ssl_verify', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('networks', 'ssl_verify')
    op.drop_column('networks', 'ssl')
    ### end Alembic commands ###
